//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMapLocalizations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string addBankAccount {
            get {
                return ResourceManager.GetString("addBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string addCreditCard {
            get {
                return ResourceManager.GetString("addCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string addInventory {
            get {
                return ResourceManager.GetString("addInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Load.
        /// </summary>
        internal static string addload {
            get {
                return ResourceManager.GetString("addload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string addparkinglot {
            get {
                return ResourceManager.GetString("addparkinglot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        internal static string bankaccount {
            get {
                return ResourceManager.GetString("bankaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking LOT.
        /// </summary>
        internal static string Create_New_Parking_LOT {
            get {
                return ResourceManager.GetString("Create New Parking LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string creditcard {
            get {
                return ResourceManager.GetString("creditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editBankAccount {
            get {
                return ResourceManager.GetString("editBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string editCreditCard {
            get {
                return ResourceManager.GetString("editCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        internal static string facility {
            get {
                return ResourceManager.GetString("facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string InventoryRevenue {
            get {
                return ResourceManager.GetString("InventoryRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string inventory_load {
            get {
                return ResourceManager.GetString("inventory-load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire.
        /// </summary>
        internal static string inventory_tire {
            get {
                return ResourceManager.GetString("inventory-tire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Setting.
        /// </summary>
        internal static string logosetting {
            get {
                return ResourceManager.GetString("logosetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Search.
        /// </summary>
        internal static string lotinfo {
            get {
                return ResourceManager.GetString("lotinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Lots.
        /// </summary>
        internal static string lots {
            get {
                return ResourceManager.GetString("lots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTE.
        /// </summary>
        internal static string PTE {
            get {
                return ResourceManager.GetString("PTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        internal static string Spaces {
            get {
                return ResourceManager.GetString("Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stakeholders.
        /// </summary>
        internal static string Stakeholders {
            get {
                return ResourceManager.GetString("Stakeholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeLine.
        /// </summary>
        internal static string TimeLine {
            get {
                return ResourceManager.GetString("TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to DeliveryNotes.
        /// </summary>
        internal static string DeliveryNotes
        {
            get {
                return ResourceManager.GetString("DeliveryNotes", resourceCulture);
            }
        }
            /// <summary>
        ///   Looks up a localized string similar to AddDeliveryNote.
        /// </summary>
        internal static string AddDeliveryNote
        {
            get {
                return ResourceManager.GetString("AddDeliveryNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProductSelection.
        /// </summary>
        internal static string ProductSelection
        {
            get
            {
                return ResourceManager.GetString("ProductSelection", resourceCulture);
            }
        }
    }
}
