//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerbarLib.ResourceManager.Resources.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerbarLib.ResourceManager.Resources.Controls.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-WEEK IRONMAN TRAINING GUIDE &amp; NUTRITION.
        /// </summary>
        internal static string _29_week_ironman_training_guide_nutrition {
            get {
                return ResourceManager.GetString("_29_week_ironman_training_guide_nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29 Week Training.
        /// </summary>
        internal static string _29_week_training {
            get {
                return ResourceManager.GetString("_29_week_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string _private {
            get {
                return ResourceManager.GetString("private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expert.
        /// </summary>
        internal static string add_expert {
            get {
                return ResourceManager.GetString("add_expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add FAQ.
        /// </summary>
        internal static string add_faq {
            get {
                return ResourceManager.GetString("add_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string add_member {
            get {
                return ResourceManager.GetString("add_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Video ID.
        /// </summary>
        internal static string add_video_id {
            get {
                return ResourceManager.GetString("add_video_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Week.
        /// </summary>
        internal static string add_week {
            get {
                return ResourceManager.GetString("add_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Comments.
        /// </summary>
        internal static string allow_comments {
            get {
                return ResourceManager.GetString("allow_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Image:.
        /// </summary>
        internal static string article_image {
            get {
                return ResourceManager.GetString("article_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARTICLE INDEX.
        /// </summary>
        internal static string article_index {
            get {
                return ResourceManager.GetString("article_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARTICLE SUMMARY.
        /// </summary>
        internal static string article_summary {
            get {
                return ResourceManager.GetString("article_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Expert FAQ.
        /// </summary>
        internal static string ask_expert_faq {
            get {
                return ResourceManager.GetString("ask_expert_faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 4.
        /// </summary>
        internal static string audience_4 {
            get {
                return ResourceManager.GetString("audience_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience 5.
        /// </summary>
        internal static string audience_5 {
            get {
                return ResourceManager.GetString("audience_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Image:.
        /// </summary>
        internal static string author_image {
            get {
                return ResourceManager.GetString("author_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name:.
        /// </summary>
        internal static string author_name {
            get {
                return ResourceManager.GetString("author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string authors {
            get {
                return ResourceManager.GetString("authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basketball.
        /// </summary>
        internal static string basketball {
            get {
                return ResourceManager.GetString("basketball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        internal static string bio {
            get {
                return ResourceManager.GetString("bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Address.
        /// </summary>
        internal static string blog_address {
            get {
                return ResourceManager.GetString("blog_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Comments.
        /// </summary>
        internal static string blog_comments {
            get {
                return ResourceManager.GetString("blog_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Description.
        /// </summary>
        internal static string blog_description {
            get {
                return ResourceManager.GetString("blog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Group.
        /// </summary>
        internal static string blog_group {
            get {
                return ResourceManager.GetString("blog_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Name.
        /// </summary>
        internal static string blog_name {
            get {
                return ResourceManager.GetString("blog_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Posts.
        /// </summary>
        internal static string blog_posts {
            get {
                return ResourceManager.GetString("blog_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Views.
        /// </summary>
        internal static string blog_views {
            get {
                return ResourceManager.GetString("blog_views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body:.
        /// </summary>
        internal static string body {
            get {
                return ResourceManager.GetString("body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Items are required.
        /// </summary>
        internal static string bold_items_are_required {
            get {
                return ResourceManager.GetString("bold_items_are_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brain function.
        /// </summary>
        internal static string brain_function {
            get {
                return ResourceManager.GetString("brain_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Image.
        /// </summary>
        internal static string browse_image {
            get {
                return ResourceManager.GetString("browse_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSE IMAGES.
        /// </summary>
        internal static string browse_images {
            get {
                return ResourceManager.GetString("browse_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2 Max.
        /// </summary>
        internal static string c2_max {
            get {
                return ResourceManager.GetString("c2_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Topic.
        /// </summary>
        internal static string choose_topic {
            get {
                return ResourceManager.GetString("choose_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Sort by.
        /// </summary>
        internal static string click_to_sort_by {
            get {
                return ResourceManager.GetString("click_to_sort_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaches.
        /// </summary>
        internal static string coaches {
            get {
                return ResourceManager.GetString("coaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented By.
        /// </summary>
        internal static string commented_by {
            get {
                return ResourceManager.GetString("commented_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to English Version.
        /// </summary>
        internal static string convert_to_english_version {
            get {
                return ResourceManager.GetString("convert_to_english_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to French Version.
        /// </summary>
        internal static string convert_to_french_version {
            get {
                return ResourceManager.GetString("convert_to_french_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to German version.
        /// </summary>
        internal static string convert_to_german_version {
            get {
                return ResourceManager.GetString("convert_to_german_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Article.
        /// </summary>
        internal static string create_article {
            get {
                return ResourceManager.GetString("create_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE ARTICLE.
        /// </summary>
        internal static string create_article1 {
            get {
                return ResourceManager.GetString("create_article1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Blog.
        /// </summary>
        internal static string create_new_blog {
            get {
                return ResourceManager.GetString("create_new_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Version.
        /// </summary>
        internal static string create_new_version {
            get {
                return ResourceManager.GetString("create_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Summary.
        /// </summary>
        internal static string create_summary {
            get {
                return ResourceManager.GetString("create_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SUMMAY.
        /// </summary>
        internal static string create_summay {
            get {
                return ResourceManager.GetString("create_summay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string created_by {
            get {
                return ResourceManager.GetString("created_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string creation_date {
            get {
                return ResourceManager.GetString("creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        internal static string cycle {
            get {
                return ResourceManager.GetString("cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Training.
        /// </summary>
        internal static string daily_training {
            get {
                return ResourceManager.GetString("daily_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        internal static string date_added {
            get {
                return ResourceManager.GetString("date_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string date_created {
            get {
                return ResourceManager.GetString("date_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last Modified.
        /// </summary>
        internal static string date_last_modified {
            get {
                return ResourceManager.GetString("date_last_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Uploaded.
        /// </summary>
        internal static string date_uploaded {
            get {
                return ResourceManager.GetString("date_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Language.
        /// </summary>
        internal static string default_language {
            get {
                return ResourceManager.GetString("default_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Featured.
        /// </summary>
        internal static string delete_featured {
            get {
                return ResourceManager.GetString("delete_featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny Comments.
        /// </summary>
        internal static string deny_comments {
            get {
                return ResourceManager.GetString("deny_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Post.
        /// </summary>
        internal static string disable_post {
            get {
                return ResourceManager.GetString("disable_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable User.
        /// </summary>
        internal static string disable_user {
            get {
                return ResourceManager.GetString("disable_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussions.
        /// </summary>
        internal static string discussions {
            get {
                return ResourceManager.GetString("discussions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duning.
        /// </summary>
        internal static string duning {
            get {
                return ResourceManager.GetString("duning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit / Expand.
        /// </summary>
        internal static string edit_expand {
            get {
                return ResourceManager.GetString("edit_expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Training.
        /// </summary>
        internal static string edit_training {
            get {
                return ResourceManager.GetString("edit_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string email_address {
            get {
                return ResourceManager.GetString("email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed Code:.
        /// </summary>
        internal static string embed_code {
            get {
                return ResourceManager.GetString("embed_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Advice.
        /// </summary>
        internal static string enable_advice {
            get {
                return ResourceManager.GetString("enable_advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Blog.
        /// </summary>
        internal static string enable_blog {
            get {
                return ResourceManager.GetString("enable_blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Post.
        /// </summary>
        internal static string enable_post {
            get {
                return ResourceManager.GetString("enable_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable User.
        /// </summary>
        internal static string enable_user {
            get {
                return ResourceManager.GetString("enable_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Version.
        /// </summary>
        internal static string english_version {
            get {
                return ResourceManager.GetString("english_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Article body.
        /// </summary>
        internal static string enter_article_body {
            get {
                return ResourceManager.GetString("enter_article_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Article Summary.
        /// </summary>
        internal static string enter_article_summary {
            get {
                return ResourceManager.GetString("enter_article_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Author Name.
        /// </summary>
        internal static string enter_author_name {
            get {
                return ResourceManager.GetString("enter_author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter daily Training info .
        /// </summary>
        internal static string enter_daily_training_info {
            get {
                return ResourceManager.GetString("enter_daily_training_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Title.
        /// </summary>
        internal static string enter_title {
            get {
                return ResourceManager.GetString("enter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL without special characters.
        /// </summary>
        internal static string enter_url_without_special_characters {
            get {
                return ResourceManager.GetString("enter_url_without_special_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Promoter.
        /// </summary>
        internal static string event_promoter {
            get {
                return ResourceManager.GetString("event_promoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded view.
        /// </summary>
        internal static string expanded_view {
            get {
                return ResourceManager.GetString("expanded_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string expert {
            get {
                return ResourceManager.GetString("expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert FAQs.
        /// </summary>
        internal static string expert_faqs {
            get {
                return ResourceManager.GetString("expert_faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ Preview.
        /// </summary>
        internal static string faq_preview {
            get {
                return ResourceManager.GetString("faq_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        internal static string featured {
            get {
                return ResourceManager.GetString("featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by:.
        /// </summary>
        internal static string filter_by {
            get {
                return ResourceManager.GetString("filter_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRSTNAME.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        internal static string fitness {
            get {
                return ResourceManager.GetString("fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluides.
        /// </summary>
        internal static string fluides {
            get {
                return ResourceManager.GetString("fluides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Note:.
        /// </summary>
        internal static string footer_note {
            get {
                return ResourceManager.GetString("footer_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundation.
        /// </summary>
        internal static string foundation {
            get {
                return ResourceManager.GetString("foundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Version.
        /// </summary>
        internal static string french_version {
            get {
                return ResourceManager.GetString("french_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun Fact.
        /// </summary>
        internal static string fun_fact {
            get {
                return ResourceManager.GetString("fun_fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery:.
        /// </summary>
        internal static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Version.
        /// </summary>
        internal static string german_version {
            get {
                return ResourceManager.GetString("german_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        internal static string getting_started {
            get {
                return ResourceManager.GetString("getting_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline:.
        /// </summary>
        internal static string headline {
            get {
                return ResourceManager.GetString("headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be between 60 and 300.
        /// </summary>
        internal static string height_must_be_between_60_and_300 {
            get {
                return ResourceManager.GetString("height_must_be_between_60_and_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string hidden {
            get {
                return ResourceManager.GetString("hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in community aggregate.
        /// </summary>
        internal static string include_in_community_aggregate {
            get {
                return ResourceManager.GetString("include_in_community_aggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Posts.
        /// </summary>
        internal static string index_posts {
            get {
                return ResourceManager.GetString("index_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influencer User.
        /// </summary>
        internal static string influencer_user {
            get {
                return ResourceManager.GetString("influencer_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ironman.
        /// </summary>
        internal static string ironman {
            get {
                return ResourceManager.GetString("ironman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string job_title {
            get {
                return ResourceManager.GetString("job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords: .
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LASTNAME.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Featured .
        /// </summary>
        internal static string make_featured {
            get {
                return ResourceManager.GetString("make_featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Private.
        /// </summary>
        internal static string make_private {
            get {
                return ResourceManager.GetString("make_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Public.
        /// </summary>
        internal static string make_public {
            get {
                return ResourceManager.GetString("make_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Registered User.
        /// </summary>
        internal static string make_registered_user {
            get {
                return ResourceManager.GetString("make_registered_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Blog Posts.
        /// </summary>
        internal static string manage_blog_posts {
            get {
                return ResourceManager.GetString("manage_blog_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Blogs.
        /// </summary>
        internal static string manage_blogs {
            get {
                return ResourceManager.GetString("manage_blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Galleries.
        /// </summary>
        internal static string manage_galleries {
            get {
                return ResourceManager.GetString("manage_galleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Groups.
        /// </summary>
        internal static string manage_groups {
            get {
                return ResourceManager.GetString("manage_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketting Title.
        /// </summary>
        internal static string marketting_title {
            get {
                return ResourceManager.GetString("marketting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Stories(Archived).
        /// </summary>
        internal static string more_stories_archived {
            get {
                return ResourceManager.GetString("more_stories_archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Expert(s) found.
        /// </summary>
        internal static string no_experts_found {
            get {
                return ResourceManager.GetString("no_experts_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subscription(s) found.
        /// </summary>
        internal static string no_subscriptions_found {
            get {
                return ResourceManager.GetString("no_subscriptions_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Video(s) found.
        /// </summary>
        internal static string no_videos_found {
            get {
                return ResourceManager.GetString("no_videos_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No weeks(s) found.
        /// </summary>
        internal static string no_weeks_found {
            get {
                return ResourceManager.GetString("no_weeks_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition Article .
        /// </summary>
        internal static string nutrition_article {
            get {
                return ResourceManager.GetString("nutrition_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Experts.
        /// </summary>
        internal static string our_experts {
            get {
                return ResourceManager.GetString("our_experts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (PBSNAB).
        /// </summary>
        internal static string pbsnab {
            get {
                return ResourceManager.GetString("pbsnab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEP.
        /// </summary>
        internal static string pep {
            get {
                return ResourceManager.GetString("pep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Title.
        /// </summary>
        internal static string photo_title {
            get {
                return ResourceManager.GetString("photo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string photos {
            get {
                return ResourceManager.GetString("photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels:.
        /// </summary>
        internal static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description.
        /// </summary>
        internal static string please_enter_description {
            get {
                return ResourceManager.GetString("please_enter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter embed code.
        /// </summary>
        internal static string please_enter_embed_code {
            get {
                return ResourceManager.GetString("please_enter_embed_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter height.
        /// </summary>
        internal static string please_enter_height {
            get {
                return ResourceManager.GetString("please_enter_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter keywords.
        /// </summary>
        internal static string please_enter_keywords {
            get {
                return ResourceManager.GetString("please_enter_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter keywords to search.
        /// </summary>
        internal static string please_enter_keywords_to_search {
            get {
                return ResourceManager.GetString("please_enter_keywords_to_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Nutrition Article.
        /// </summary>
        internal static string please_enter_nutrition_article {
            get {
                return ResourceManager.GetString("please_enter_nutrition_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Summary of training.
        /// </summary>
        internal static string please_enter_summary_of_training {
            get {
                return ResourceManager.GetString("please_enter_summary_of_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the answer.
        /// </summary>
        internal static string please_enter_the_answer {
            get {
                return ResourceManager.GetString("please_enter_the_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the author name.
        /// </summary>
        internal static string please_enter_the_author_name {
            get {
                return ResourceManager.GetString("please_enter_the_author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Bio.
        /// </summary>
        internal static string please_enter_the_bio {
            get {
                return ResourceManager.GetString("please_enter_the_bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the blog description.
        /// </summary>
        internal static string please_enter_the_blog_description {
            get {
                return ResourceManager.GetString("please_enter_the_blog_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Blog name.
        /// </summary>
        internal static string please_enter_the_blog_name {
            get {
                return ResourceManager.GetString("please_enter_the_blog_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the expert&apos;s name.
        /// </summary>
        internal static string please_enter_the_experts_name {
            get {
                return ResourceManager.GetString("please_enter_the_experts_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the fun fact.
        /// </summary>
        internal static string please_enter_the_fun_fact {
            get {
                return ResourceManager.GetString("please_enter_the_fun_fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name.
        /// </summary>
        internal static string please_enter_the_name {
            get {
                return ResourceManager.GetString("please_enter_the_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the question.
        /// </summary>
        internal static string please_enter_the_question {
            get {
                return ResourceManager.GetString("please_enter_the_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter title.
        /// </summary>
        internal static string please_enter_title {
            get {
                return ResourceManager.GetString("please_enter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter title of training.
        /// </summary>
        internal static string please_enter_title_of_training {
            get {
                return ResourceManager.GetString("please_enter_title_of_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter width.
        /// </summary>
        internal static string please_enter_width {
            get {
                return ResourceManager.GetString("please_enter_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a week to add detail.
        /// </summary>
        internal static string please_select_a_week_to_add_detail {
            get {
                return ResourceManager.GetString("please_select_a_week_to_add_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image to upload.
        /// </summary>
        internal static string please_select_an_image_to_upload {
            get {
                return ResourceManager.GetString("please_select_an_image_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select at least one Related sport.
        /// </summary>
        internal static string please_select_at_least_one_related_sport {
            get {
                return ResourceManager.GetString("please_select_at_least_one_related_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select at least one Related Top.
        /// </summary>
        internal static string please_select_at_least_one_related_top {
            get {
                return ResourceManager.GetString("please_select_at_least_one_related_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select at least one Related Topic.
        /// </summary>
        internal static string please_select_at_least_one_related_topic {
            get {
                return ResourceManager.GetString("please_select_at_least_one_related_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one sport.
        /// </summary>
        internal static string please_select_at_least_one_sport {
            get {
                return ResourceManager.GetString("please_select_at_least_one_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one related topic.
        /// </summary>
        internal static string please_select_atleast_one_related_topic {
            get {
                return ResourceManager.GetString("please_select_atleast_one_related_topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select category.
        /// </summary>
        internal static string please_select_category {
            get {
                return ResourceManager.GetString("please_select_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Rights.
        /// </summary>
        internal static string please_select_rights {
            get {
                return ResourceManager.GetString("please_select_rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the expert.
        /// </summary>
        internal static string please_select_the_expert {
            get {
                return ResourceManager.GetString("please_select_the_expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select training.
        /// </summary>
        internal static string please_select_training {
            get {
                return ResourceManager.GetString("please_select_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select training to Preview.
        /// </summary>
        internal static string please_select_training_to_preview {
            get {
                return ResourceManager.GetString("please_select_training_to_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select video to add VideoID.
        /// </summary>
        internal static string please_select_video_to_add_videoid {
            get {
                return ResourceManager.GetString("please_select_video_to_add_videoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select video to upload.
        /// </summary>
        internal static string please_select_video_to_upload {
            get {
                return ResourceManager.GetString("please_select_video_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string posts {
            get {
                return ResourceManager.GetString("posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerBar:.
        /// </summary>
        internal static string powerbar {
            get {
                return ResourceManager.GetString("powerbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre.
        /// </summary>
        internal static string pre {
            get {
                return ResourceManager.GetString("pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation.
        /// </summary>
        internal static string preparation {
            get {
                return ResourceManager.GetString("preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string prev {
            get {
                return ResourceManager.GetString("prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Sport.
        /// </summary>
        internal static string primary_sport {
            get {
                return ResourceManager.GetString("primary_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Tips.
        /// </summary>
        internal static string pro_tips {
            get {
                return ResourceManager.GetString("pro_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category:.
        /// </summary>
        internal static string product_category {
            get {
                return ResourceManager.GetString("product_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Management.
        /// </summary>
        internal static string profile_management {
            get {
                return ResourceManager.GetString("profile_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question (first 30 char).
        /// </summary>
        internal static string question_first_30_char {
            get {
                return ResourceManager.GetString("question_first_30_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string recovery {
            get {
                return ResourceManager.GetString("recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Sports.
        /// </summary>
        internal static string related_sports {
            get {
                return ResourceManager.GetString("related_sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Topics:.
        /// </summary>
        internal static string related_topics {
            get {
                return ResourceManager.GetString("related_topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUN.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Name.
        /// </summary>
        internal static string screen_name {
            get {
                return ResourceManager.GetString("screen_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Country:.
        /// </summary>
        internal static string search_by_country {
            get {
                return ResourceManager.GetString("search_by_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Primary Sports:.
        /// </summary>
        internal static string search_by_primary_sports {
            get {
                return ResourceManager.GetString("search_by_primary_sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Keywords.
        /// </summary>
        internal static string search_keywords {
            get {
                return ResourceManager.GetString("search_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string section {
            get {
                return ResourceManager.GetString("section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one Audience.
        /// </summary>
        internal static string select_at_least_one_audience {
            get {
                return ResourceManager.GetString("select_at_least_one_audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one Category.
        /// </summary>
        internal static string select_at_least_one_category {
            get {
                return ResourceManager.GetString("select_at_least_one_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one theme.
        /// </summary>
        internal static string select_at_least_one_theme {
            get {
                return ResourceManager.GetString("select_at_least_one_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        internal static string shape {
            get {
                return ResourceManager.GetString("shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Answer.
        /// </summary>
        internal static string short_answer {
            get {
                return ResourceManager.GetString("short_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Question.
        /// </summary>
        internal static string short_question {
            get {
                return ResourceManager.GetString("short_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skills.
        /// </summary>
        internal static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport 1.
        /// </summary>
        internal static string sport_1 {
            get {
                return ResourceManager.GetString("sport_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport 2.
        /// </summary>
        internal static string sport_2 {
            get {
                return ResourceManager.GetString("sport_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport 3.
        /// </summary>
        internal static string sport_3 {
            get {
                return ResourceManager.GetString("sport_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport 4.
        /// </summary>
        internal static string sport_4 {
            get {
                return ResourceManager.GetString("sport_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina.
        /// </summary>
        internal static string stamina {
            get {
                return ResourceManager.GetString("stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string strength {
            get {
                return ResourceManager.GetString("strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Preview.
        /// </summary>
        internal static string summary_preview {
            get {
                return ResourceManager.GetString("summary_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        internal static string supplements {
            get {
                return ResourceManager.GetString("supplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIM.
        /// </summary>
        internal static string swim {
            get {
                return ResourceManager.GetString("swim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Audience:.
        /// </summary>
        internal static string target_audience {
            get {
                return ResourceManager.GetString("target_audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Elite.
        /// </summary>
        internal static string team_elite {
            get {
                return ResourceManager.GetString("team_elite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team in Training.
        /// </summary>
        internal static string team_in_training {
            get {
                return ResourceManager.GetString("team_in_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail: .
        /// </summary>
        internal static string thumbnail {
            get {
                return ResourceManager.GetString("thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 Stories.
        /// </summary>
        internal static string top_5_stories {
            get {
                return ResourceManager.GetString("top_5_stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Preview.
        /// </summary>
        internal static string training_preview {
            get {
                return ResourceManager.GetString("training_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tri.
        /// </summary>
        internal static string tri {
            get {
                return ResourceManager.GetString("tri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Page.
        /// </summary>
        internal static string untitled_page {
            get {
                return ResourceManager.GetString("untitled_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Full Name: .
        /// </summary>
        internal static string user_full_name {
            get {
                return ResourceManager.GetString("user_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Subscriptions.
        /// </summary>
        internal static string user_subscriptions {
            get {
                return ResourceManager.GetString("user_subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        internal static string user_type {
            get {
                return ResourceManager.GetString("user_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video:.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video ID.
        /// </summary>
        internal static string video_id {
            get {
                return ResourceManager.GetString("video_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string videos {
            get {
                return ResourceManager.GetString("videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Comments.
        /// </summary>
        internal static string view_comments {
            get {
                return ResourceManager.GetString("view_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string view_details {
            get {
                return ResourceManager.GetString("view_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string views {
            get {
                return ResourceManager.GetString("views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Address.
        /// </summary>
        internal static string web_address {
            get {
                return ResourceManager.GetString("web_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week by Week Training.
        /// </summary>
        internal static string week_by_week_training {
            get {
                return ResourceManager.GetString("week_by_week_training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must be between 60 and 300.
        /// </summary>
        internal static string width_must_be_between_60_and_300 {
            get {
                return ResourceManager.GetString("width_must_be_between_60_and_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorldWide.
        /// </summary>
        internal static string worldwide {
            get {
                return ResourceManager.GetString("worldwide", resourceCulture);
            }
        }
    }
}
